version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sistemaloja-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlServer2024!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./setup.sql:/setup.sql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SqlServer2024! -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - loja-network

  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sistemaloja-sqlserver-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./setup.sql:/setup.sql
    entrypoint: /bin/bash
    command: >
      -c "
      echo 'Aguardando SQL Server ficar pronto...';
      sleep 5;
      echo 'Executando script de inicialização...';
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'SqlServer2024!' -i /setup.sql -C;
      echo 'Banco de dados configurado com sucesso!';
      "
    networks:
      - loja-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistemaloja-app
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SQL_SERVER=sqlserver
    stdin_open: true
    tty: true
    networks:
      - loja-network

volumes:
  sqlserver-data:

networks:
  loja-network:
    driver: bridge
